agent:
  id: "vehicle_1"
  type: "dqn"

  state_space:
    dimensions: 52
  action_space:
    dimensions: 17
    mapping: { 0: "0", 1: "1", 2: "2", 3: "3", 4: "4", 5: "5",
               6: "6", 7: "7", 8: "8", 9: "9", 10: "10", 11: "11",
               12: "12", 13: "13", 14: "14", 15: "15", 16: "16" }
  dqn:
    state_dim: 52
    action_dim: 17
    gamma: 0.95
    learning_rate: 0.001
    train_frequency: 1

    memory_capacity: 1000
    batch_size: 32
    min_memory_size: 32
    tau_start: 1
    tau_end: 0.1
    tau_decay: 0.95
    fedavg_include: ["a_head", "v_head"]

  network:
    vehicle_feat_dim: 4
    server_feat_dim: 3
    n_servers: 16
    